### ISSUE TITLE
cocoapods version 2.1.6 is broken

### ISSUE THREAD

**Issue by pbarilla** [kevin-hirsch/KVNProgress#19]
First up, thanks for a great library! :-)

Anyways, trying to install (or update an existing install) by using the following line in the podfile
```
pod 'KVNProgress'
```
gives a warning that pods cannot find the Pods/KVNProgress/LICENSE file. Additionally, Xcode cannot compile as it is missing a file KVNProgressConfiguration.h.

changing podfile line to
```
pod 'KVNProgress', '2.1.4'
```
resolves issue

**Comment by kevin-hirsch** [comment]
Thanks for your support and for noticing :)

So what you say is that having `pod 'KVNProgress'` in the Podfile and then you do a `pod install` or `pod update` and the command returns you the missing files error?

I will look at this issue in priority!

**Comment by pbarilla** [comment]
thats right. if you force it to use 2.1.4, it works as intended. 
Thanks! :)

**Comment by kevin-hirsch** [comment]
Can you confirm that all is working well now? :)

**Comment by pbarilla** [comment]
Tested it earlier today, it's working perfectly. Thanks again :)

**Comment by kevin-hirsch** [comment]
Thank you very much! I am closing this issue then ;)
