### ISSUE TITLE
"Infinity progress" freeze after application did become active. 

### ISSUE THREAD

**Issue by korzun1993** [kevin-hirsch/KVNProgress#23]

**Comment by kevin-hirsch** [comment]
What you mean by freeze? The ring is not animating?

**Comment by korzun1993** [comment]
Exactly, I add handler for  "applicationDidBecomeActive" notification and call method animateCircleWithInfiniteLoop in it, and it helps but I am not sure that this is best solution.

**Comment by kevin-hirsch** [comment]
I search for a good solution but I don't find a better than this one. Thanks for the proposition. Your pull request is now merged! I just refactored it a little to keep the same structure in all the project ;)
