### ISSUE TITLE
Compiling issue Xcode 5.1

### ISSUE THREAD

**Issue by foffux** [kevin-hirsch/KVNProgress#24]
Into KVNProgress.m class, into rotationForStatusBarOrientation method, you defined:

case UIInterfaceOrientationUnknown:

But with Xcode 5.1 this will give me a compiler error. Take a look:

- (CGFloat)rotationForStatusBarOrientation {
	switch ([UIApplication sharedApplication].statusBarOrientation) {
		case UIInterfaceOrientationLandscapeLeft:
			return -M_PI_2;
		case UIInterfaceOrientationLandscapeRight:
			return M_PI_2;
		case UIInterfaceOrientationPortraitUpsideDown:
			return M_PI;
		case UIInterfaceOrientationPortrait:
		case UIInterfaceOrientationUnknown:
			return 0;
	}
}

Just remove "case UIInterfaceOrientationUnknown:", it has no sense. In my understanding.

**Comment by kevin-hirsch** [comment]
What is the compiler error you got?
I put this case because it was part of the enum and I prefer handle all enum cases in a switch to avoid forgot about one.

**Comment by foffux** [comment]
Hello
Have a look at two pictures I attached. Moreover, storyboard you did complains about Xcode 5, it wants Xcode 6.
Hope this helps.
![schermata 2015-01-31 alle 09 45 05](https://cloud.githubusercontent.com/assets/8709479/5987510/24a77ab0-a92e-11e4-9dd5-f82f39fc16ea.png)
![schermata 2015-01-31 alle 09 45 32](https://cloud.githubusercontent.com/assets/8709479/5987511/24ab037e-a92e-11e4-88dd-5893611ea169.png)

**Comment by kevin-hirsch** [comment]
Why do you need Xcode 5.1?
I do not think I am going to make it compatible with Xcode 5 because we'll soon have to use Xcode 6 to use iOS 8 SDK. As Apple said:

> As we announced in October, beginning February 1, 2015 new iOS apps submitted to the App Store must include 64-bit support and be built with the iOS 8 SDK. Beginning June 1, 2015 app updates will also need to follow the same requirements. To enable 64-bit in your project, we recommend using the default Xcode build setting of “Standard architectures” to build a single binary with both 32-bit and 64-bit code.

**Comment by foffux** [comment]
Ok I agree and I think I will shift to Xcode 6 soon. I thought you wanted
to have also this compatibility. If you do not, no problem.

2015-02-04 22:28 GMT+01:00 Kevin Hirsch <notifications@github.com>:

**Comment by kevin-hirsch** [comment]
Yes I will stay with Xcode 6 compatibility but I will change my README.md which precise Xcode 5. Thanks!

**Comment by foffux** [comment]
Ok that information in readme file does not cost anything :-)
good job anyway

2015-02-05 9:06 GMT+01:00 Kevin Hirsch <notifications@github.com>:

**Comment by kevin-hirsch** [comment]
Thank you! :)
