### ISSUE TITLE
App crashing when trying to set value

### ISSUE THREAD

**Issue by SolomonBier** [kevin-hirsch/KVNProgress#26]
[KVNProgress showWithStatus:@"Loading"]; //produces below error

Error: 
*** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<KVNProgress 0x15554d1b0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key contentViewLeadingToSuperviewConstraint.'

**Comment by kevin-hirsch** [comment]
Which version of `KVNProgress` are you using?

**Comment by kevin-hirsch** [comment]
@SolomonBier, any updates on this issue?

**Comment by SolomonBier** [comment]
@kevin-hirsch updated to newer version and issue disappeared. Closing !
