### ISSUE TITLE
Crash with iOS SDK 8.1, KVNProgress 2.1.8

### ISSUE THREAD

**Issue by foffux** [kevin-hirsch/KVNProgress#28]
A crash I have never seen with previous versions both iOS SDK and KVNProgress
Crash occurs here:

In KVNProgress.m
self.backgroundImageView.image = [UIImage emptyImage];

+[UIImage emptyImage]: unrecognized selector sent to class 0x2a2c2cc
 see log at the end

solve using this line of code:
self.backgroundImageView.image = [[UIImage alloc] init];

Could you please try to fix it in your whole architecture?
Thank you very much.

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[UIImage emptyImage]: unrecognized selector sent to class 0x2a2c2cc'
*** First throw call stack:
(
	0   CoreFoundation                      0x035bd1e4 __exceptionPreprocess + 180
	1   libobjc.A.dylib                     0x0323d8e5 objc_exception_throw + 44
	2   CoreFoundation                      0x0365a0e3 +[NSObject(NSObject) doesNotRecognizeSelector:] + 275
	3   CoreFoundation                      0x035ad50b ___forwarding___ + 1019
	4   CoreFoundation                      0x035ad0ee _CF_forwarding_prep_0 + 14
	5   Angel                               0x00180bfc -[KVNProgress updateBackground] + 2028
	6   Angel                               0x0017f783 -[KVNProgress setupBackground] + 115
	7   Angel                               0x0017afa9 -[KVNProgress setupUI] + 201
	8   Angel                               0x00179480 -[KVNProgress showProgress:status:style:backgroundType:fullScreen:view:completion:] + 2912
	9   Angel                               0x001788b0 +[KVNProgress showHUDWithProgress:style:status:superview:completion:] + 336
	10  Angel                               0x00177cb3 +[KVNProgress showWithStatus:onView:] + 179
	11  Angel                               0x00177bdc +[KVNProgress showWithStatus:] + 108
	12  Angel                               0x00025a4d -[RMAMapsViewController viewDidLoad] + 397
	13  UIKit                               0x0201733d -[UIViewController loadViewIfRequired] + 696
	14  UIKit                               0x0203d345 -[UINavigationController _layoutViewController:] + 39
	15  UIKit                               0x0203d85b -[UINavigationController _updateScrollViewFromViewController:toViewController:] + 235
	16  UIKit                               0x0203d953 -[UINavigationController _startTransition:fromViewController:toViewController:] + 78
	17  UIKit                               0x0203e8cc -[UINavigationController _startDeferredTransitionIfNeeded:] + 645
	18  UIKit                               0x0203f4e9 -[UINavigationController __viewWillLayoutSubviews] + 57
	19  UIKit                               0x021800d1 -[UILayoutContainerView layoutSubviews] + 213
	20  UIKit                               0x01f67964 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 355
	21  libobjc.A.dylib                     0x0324f82b -[NSObject performSelector:withObject:] + 70
	22  QuartzCore                          0x0096645a -[CALayer layoutSublayers] + 148
	23  QuartzCore                          0x0095a244 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 380
	24  QuartzCore                          0x0095a0b0 _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 26
	25  QuartzCore                          0x008c07fa _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 294
	26  QuartzCore                          0x008c1b85 _ZN2CA11Transaction6commitEv + 393
	27  QuartzCore                          0x008c2258 _ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv + 92
	28  CoreFoundation                      0x0358536e __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 30
	29  CoreFoundation                      0x035852bf __CFRunLoopDoObservers + 399
	30  CoreFoundation                      0x03563254 __CFRunLoopRun + 1076
	31  CoreFoundation                      0x035629d3 CFRunLoopRunSpecific + 467
	32  CoreFoundation                      0x035627eb CFRunLoopRunInMode + 123
	33  GraphicsServices                    0x047885ee GSEventRunModal + 192
	34  GraphicsServices                    0x0478842b GSEventRun + 104
	35  UIKit                               0x01ef8f9b UIApplicationMain + 1225
	36  Angel                               0x000359ad main + 141
	37  libdyld.dylib                       0x03ec4701 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by foffux** [comment]
To give another clue, here what I did to avoid the issue. Simply add UIImage+KVNEmpty.m into my main project as resource to be compiled, even if it was already added to pods related project. I think it was not good at all and this happens just with new iOS 8 SDK (Xcode 6). Maybe a issue related to cocoa pods? I am using latest version, 0.35.0.
I think someone should look after this issue because it is not possible I am the only one experimenting this problem.
See also this issue I saw in another third-party controller

https://github.com/michaeltyson/TPKeyboardAvoiding/issues/75

It is the same issue I can see here, after updating to Xcode 6.

I am looking forward to an answer.
Thank you.

**Comment by foffux** [comment]
Based on what I told in
[TPKeyboardAvoidingScrollView TPKeyboardAvoiding_updateContentInset]: unrecognized selector sent to instance #75
I guess this issue can be closed. Hope this helps someone else.

**Comment by foffux** [comment]
Link:
michaeltyson/TPKeyboardAvoiding#75

**Comment by kevin-hirsch** [comment]
Thanks for the info @foffux!
I will add "-ObjC" to the Linker Flags and make a new version of the pod tonight.

**Comment by foffux** [comment]
You can also check this answer

http://stackoverflow.com/questions/26445784/target-overrides-the-framework-search-paths-build-settings

maybe it was the actual cause of all my problems...Anyway, it were two days of workarounds to fix issues related to Xcode 6 and stuff related...

**Comment by kevin-hirsch** [comment]
Thanks! :+1:

**Comment by kevin-hirsch** [comment]
Fixed in commit eb0c84439e880b20a66bcb036c6fb11358997155

**Comment by foffux** [comment]
Hello kevin. Sorry for annoying you. I had to open another issue. With iOS
8 the progress HUD is not showing anymore even if I am using the same code
that works for iOS 7. I tried to explain in the issue. If you could have a
look and try to fix it it would be very nice. Tell me if you need
something. Thank you very much

Il venerdì 13 febbraio 2015, Kevin Hirsch <notifications@github.com> ha
scritto:
