### ISSUE TITLE
Adding Animated Flag To Presentation (show) And Dismissing (hide)

### ISSUE THREAD

**Issue by joeblau** [kevin-hirsch/KVNProgress#36]
I was thinking about modifying this library to allow toggling of animations like iOS's native UI View Controllers.  Right now the KVNLayoutAnimationDuration property is not exposed and what I'm proposing would be a major version point release breaking change.

Essentially, I want to propose adding an animated flag to all shows/dismisses in KVN just like apple exposes on its [View Controller](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIViewController_Class/#//apple_ref/occ/instm/UIViewController/presentViewController:animated:completion:) presentation
```objective-c
// Present
- (void)presentViewController:(UIViewController *)viewControllerToPresent
                     animated:(BOOL)flag
                   completion:(void (^)(void))completion
// Dismiss
- (void)dismissViewControllerAnimated:(BOOL)flag
                           completion:(void (^)(void))completion
```

With an `animated` property, I'm proposing changing all of the show/hide calls of KVN to have an animated property.  Like I mentioned above, this would break anyone using a 2.x version of the application so it would also require a version bump.

What do you think about this?

**Comment by kevin-hirsch** [comment]
Hello @joeblau,

Thank you for your proposal. I am just wondering what could be the benefit of that. Why would we want to show the HUD in a non animated way? Do you need this feature for something special?
Also, when possible, I would like to keep `KVNProgress` calls shorts (`[KVNProgress show]`, `[KVNProgress dismiss]`, `[KVNProgress showWithStatus:@""]`).

**Comment by joeblau** [comment]
Right now I have a case where I navigate to a View Controller and there is information on that screen.  I want to block the user from modifying the screen and show the KVNProgress modally which I can do, but only in an animated fashion.  I evaluate whether or not KVNProgress should be shown when the view loads, but I can't show the view without an animation so it looks like a glitch where the view loads and then the KVNProgress animates in on top.

![kvnprogress](https://cloud.githubusercontent.com/assets/1218847/7405196/3e7364d4-eea4-11e4-9b4e-c4068d57953d.gif)

I understand the desire to keep the classes short, but this is Objective-C land we're in :).  The change would also fall in line with how Apple presents and dismisses views where you can control whether or not you want them animated.

**Comment by kevin-hirsch** [comment]
Would it not okay to show the `KVNProgress` when you click on "Finish Quiz" and then, behind the HUD push to the next screen?

**Comment by joeblau** [comment]
I can, but the quiz state can be altered from the Watch or an Extension.

**Comment by joeblau** [comment]
@kevin-hirsch Actually, you know what, we can close this ticket.  I'm going to rebuild this using segues so i'll have access to the native presenting and dismissing functionality.

**Comment by kevin-hirsch** [comment]
Okay!
