### ISSUE TITLE
Pod Installation Issue 

### ISSUE THREAD

**Issue by chlebta** [kevin-hirsch/KVNProgress#42]
I'm using pod to install the library and I got this error 
![capture d ecran 2015-06-01 a 10 54 49](https://cloud.githubusercontent.com/assets/1204608/7910764/502e8e28-084f-11e5-976b-1ea8e132b538.png)

**Comment by kevin-hirsch** [comment]
Can you re-upload the screenshot, please?

**Comment by chlebta** [comment]
@kevin-hirsch  done

**Comment by kevin-hirsch** [comment]
That's strange! Did you try to remove the `/Pods` folder and to redo `pod install`?

**Comment by chlebta** [comment]
@kevin-hirsch  NO I can't remove pod folder I got some other pods any other solutions

**Comment by kevin-hirsch** [comment]
Doing `pod install` will re-install the Pods folder ;)

**Comment by chlebta** [comment]
I got some modified file in pod this why I can't delete all pods

**Comment by kevin-hirsch** [comment]
Then you can just delete KVNProgress folder inside Pods folder and do pod install ;)

**Comment by chlebta** [comment]
Than's I solved it, it there's was another var named successColor this way

**Comment by kevin-hirsch** [comment]
Okay, great!
