### ISSUE TITLE
a parameter list of without types is only allowed in a function definition

### ISSUE THREAD

**Issue by AttoLee** [kevin-hirsch/KVNProgress#43]
In a project generated by unity, I drag the files into the project, I got the error message.
![screen shot 2015-06-02 at 12 17 35 am](https://cloud.githubusercontent.com/assets/4199324/7917445/0d4a246e-08bd-11e5-9aa0-4d188657d665.png)

**Comment by kevin-hirsch** [comment]
I see 4 errors on this line, can you tell me the others?

**Comment by AttoLee** [comment]
![screen shot 2015-06-02 at 12 23 16 am](https://cloud.githubusercontent.com/assets/4199324/7917523/9a05d11e-08bd-11e5-91fc-377c74feff9c.png)

**Comment by kevin-hirsch** [comment]
The project is in Objective-C?
You should not have any problem with this line.

It's 2 macros:

```objc
#define KVNBlockSelf __blockSelf
#define KVNPrepareBlockSelf() __weak typeof(self) KVNBlockSelf = self
```

which results in:

```objc
__weak typeof(self) __blockSelf = self
```

**Comment by AttoLee** [comment]
I also see .cpp and .mm file in the project.

**Comment by AttoLee** [comment]
There is a another error, which also confuse me.
![screen shot 2015-06-02 at 12 47 27 am](https://cloud.githubusercontent.com/assets/4199324/7918035/2c17aa5c-08c1-11e5-8226-59e746a1920b.png)

**Comment by kevin-hirsch** [comment]
There shouldn't be .cpp and .mm files.
Can you show me an image of the files in for KVNProgress, please?
For the `@import`'s, see this [post](https://github.com/dogo/SCLAlertView/issues/77#issuecomment-77842437).

**Comment by AttoLee** [comment]
![screen shot 2015-06-02 at 1 08 11 am](https://cloud.githubusercontent.com/assets/4199324/7918431/e2f43090-08c3-11e5-9956-e0a12a666988.png)

**Comment by kevin-hirsch** [comment]
This seems correct.

Can you try changing:

```objc
#define KVNPrepareBlockSelf() __weak typeof(self) KVNBlockSelf = self
```

to

```objc
#define KVNPrepareBlockSelf() __weak KVNProgress *KVNBlockSelf = self
```

And tell me if it changes something?

**Comment by AttoLee** [comment]
Ok now!

**Comment by kevin-hirsch** [comment]
Ok, it's weird. I will change this in the next release.
