### ISSUE TITLE
setupStopUI is not called when the configuration is set to showStop

### ISSUE THREAD

**Issue by markfulo** [kevin-hirsch/KVNProgress#46]
It still shows the default HUD when I set the config to showStop to YES and added a block method on tapBlock and also added stopColor to red and stopRelativeHeight to 0.3f. I have added a log message on setupStopUI on KVNProgress.m but it is not called when the HUD is displayed. The stop feature is working but the stop UI is not there.

**Comment by kevin-hirsch** [comment]
Hello @markfulo,

The `setupStopUI` is only called for a determinate progress. (For that, you have to call `showProgress:...` and then `updateProgress:animated:`)
Also, the `setupStopUI` method begins with these lines of code:

```objc
if (![self.configuration doesShowStop]
		|| !self.configuration.tapBlock
		|| [configuration doesAllowUserInteraction])
	{
		return;
	}
```

That means that for the stop button to show, you have to:
- have your configuration with the `BOOL showStop` to `YES`
- not have a `tapBlock` set on the HUD
- and have the configuration `BOOL allowUserInteraction` set to YES

Does that help you?

**Comment by markfulo** [comment]
@kevin-hirsch, alright, I will test this one. Thanks!
