### ISSUE TITLE
showSuccessWithStatus layout is buggy when overlapped with UINotification registrar alert view

### ISSUE THREAD

**Issue by kublaios** [kevin-hirsch/KVNProgress#59]
After my application launches, I'm downloading data and showing the status with KVNProgress. After the download is complete, I'm showing the success status with a message.

However, if the user is launching the application for the first time and if I'm trying to register for remote notifications, the success layout behaves strange when the user taps on an option to dismiss the alert view.

This does not happen with a normal alert view, only with UINotification registrar view.

I have uploaded video capture of two instances here: https://www.youtube.com/watch?v=suegxQtywhc

I will also be pushing workarounds -if any- to this repo: https://github.com/kublaios/KVNProgressBug

Any ideas or suggestions?

**Comment by kevin-hirsch** [comment]
Hello @kublaios!

I noticed it also but I don't know what's causing this weird behaviour. I should take a look. Did you find anything yet?

**Comment by kublaios** [comment]
Unfortunately not. I can tell it does the same no matter where I call the showSuccess method, inside a block or after view appears. The strange thing is that it won't happen with UIAlertViews. I'm sure it would probably occur with alerts popped up from system like low battery etc.

**Comment by kevin-hirsch** [comment]
Should be fixed now.
When putting app on background and then foreground again, the indeterminate progress animation was stopped and I added some code to fix that but it was not checking correctly that we were in an indeterminate progress state. And so it was making the success HUD spin.
