### ISSUE TITLE
KVNBlockSelf.queue addOperation

### ISSUE THREAD

**Issue by Bosian** [kevin-hirsch/KVNProgress#72]
When enter to UIViewController, then appear "Thread 1: signal SIGABRT" and error message is below ...

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSOperationQueue addOperation:]: operation is already enqueued on a queue'

`		dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.1f * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
			if (![KVNBlockSelf.animateAppearanceOperation isFinished] && ![KVNBlockSelf.animateAppearanceOperation isExecuting]) {
				[KVNBlockSelf.queue addOperation:KVNBlockSelf.animateAppearanceOperation];
			}
		});`

**Comment by kevin-hirsch** [comment]
Hello @Bosian,

We just noticed this bug. Try updating to the latest version of the project, this should be fixed with 4b8a2c0f1e48f6bf80e4008a091dfe20b5619ad9.
You can update to pod version 2.4.4.

Please report again if you see this crash again.

**Comment by Bosian** [comment]
Amazing! It's working, Thank you!!

**Comment by animaonline** [comment]
Thanks for the fix! :+1:
