### ISSUE TITLE
Change the color of the HUD dynamically

### ISSUE THREAD

**Issue by avently** [kevin-hirsch/KVNProgress#8]
Hey, thank you for your library. Can you tell me how to change a color of "backgroundFillColor" and "circleFillBackgroundColor" dynamically? 
For example. I had set a color as red. I pressed a button and a HUD had appeared with the red color. Then i had changed the color and the color of the HUD was the same.

**Comment by kevin-hirsch** [comment]
From now on, just change the `KVNProgress.configuration.backgroundFillColor = [UIColor theColorYouWant]` to change the color dynamically.
